<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>DSHPlayer2.Stardew</RootNamespace>
    <AssemblyName>DSHPlayer2.Stardew</AssemblyName>
    <Version>0.1.0</Version>
    <Nullable>enable</Nullable>
    <ModFolderName>DSHPlayer2</ModFolderName>
    <EnableModZip>false</EnableModZip>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\player2-core\DSHPlayer2.Core.csproj" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>
</Project>
